### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by jaykorea** [neobotix/neo_local_planner#13]
Well discovered about neobotix.

Is there any advantage of using neo localplanner than teb local planner?

I am considering which planner to use with move base flex

Thank you.

**Comment by padhupradheep** [comment]
Hey, thanks for getting in touch. 

Neo local planner is an empirical local planner, which is based upon pure pursuit. There is no support for Omni drive or Ackermann drives in general. This local planner has an high accuracy of close to 1 cm.  

Whereas TEB is a predictive controller. Unlike neo_local_planner, there is a lot of optimization process involved. It also supports all the possible types of robot (I guess). But it requires a lot of tuning. The accuracy is as far as we know is not as good as the neo_local_planner because of the optimizations and the robot oscillates a lot while reaching the goal. 

If you are looking for an out of the box solution, which does not require omni-directionality then you could go with the neo_local_planner.
